feat: improve deployement workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,10 +22,19 @@ jobs:
           VPS_USER: "root"
           VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
         run: |
-          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
+          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST 'EOF'
             echo "Starting deployment..."
-            cd /root/the-tip-top-app || { echo "Directory not found"; exit 1; }
+            if [ ! -d "/root/the-tip-top-app" ]; then
+              echo "Directory not found, creating and cloning..."
+              mkdir -p /root/the-tip-top-app
+              cd /root/the-tip-top-app
+              git clone https://github.com/CapitaineCro4/the-tip-top.git .
+            else
+              cd /root/the-tip-top-app
+            fi
             git pull origin main || { echo "Git pull failed"; exit 1; }
+            # Supprime les conteneurs existants pour éviter les conflits
+            docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
             docker-compose down || { echo "Docker-compose down failed"; exit 1; }
             docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
             echo "Deployment finished!"
