chore: create preprod branch

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -167,16 +167,15 @@ jobs:
           VPS_USER: "root"
           VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
         run: |
-            sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
-                echo "Deploying to dev..."
-                cd /root/the-tip-top-app
-                git fetch origin develop
-                git reset --hard origin/develop || { echo "Git reset failed"; exit 1; }
-                docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
-                docker-compose down || { echo "Docker-compose down failed"; exit 1; }
-                docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
-                echo "Deployment to dev finished!"
-            EOF
+          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
+            echo "Deploying to dev..."
+            cd /root/the-tip-top-app
+            git fetch origin develop
+            git reset --hard origin/develop || { echo "Git reset failed"; exit 1; }
+            docker rm -f api front || true
+            docker-compose up --build -d api front || { echo "Docker-compose up failed"; exit 1; }
+            echo "Deployment to dev finished!"
+          EOF
 
       - name: Deploy to Preprod
         if: github.ref == 'refs/heads/preprod'
@@ -188,10 +187,10 @@ jobs:
           sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
             echo "Deploying to preprod..."
             cd /root/the-tip-top-app
-            git pull origin preprod || { echo "Git pull failed"; exit 1; }
-            docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
-            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
-            docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
+            git fetch origin preprod
+            git reset --hard origin/preprod || { echo "Git reset failed"; exit 1; }
+            docker rm -f api front || true
+            docker-compose up --build -d api front || { echo "Docker-compose up failed"; exit 1; }
             echo "Deployment to preprod finished!"
           EOF
 
@@ -228,9 +227,10 @@ jobs:
           sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << 'EOF'
             echo "Deploying to production..."
             cd /root/the-tip-top-app
-            git pull origin main || { echo "Git pull failed"; exit 1; }
-            docker rm -f pushgateway prometheus grafana postgres_db api front backup || true
-            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
-            docker-compose up --build -d || { echo "Docker-compose up failed"; exit 1; }
+            git fetch origin main
+            git reset --hard origin/main || { echo "Git reset failed"; exit 1; }
+            # Ne pas supprimer ou arrêter postgres_db
+            docker rm -f api front || true
+            docker-compose up --build -d api front || { echo "Docker-compose up failed"; exit 1; }
             echo "Deployment to production finished!"
           EOF
